spring.application.name=ms-prestamos
server.port=8085

# Conexión MySQL (Puerto 3307)
spring.datasource.url=jdbc:mysql://localhost:3307/library_loans_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
